#TEXT ADVENTURE SHORT STORY GAME: BY NICOLE
#06/03/2022

import sys

import time

a = 1
b = 3
c = 0.08

while True:
    print()
    print()
    print()
    print('        *    #    *    #    *    #    *     #     *     #')
    print('        *                                               #')
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    print('                         A HORROR STORY                     ')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *                                               #')
    time.sleep(c)
    print('        *    #    *    #    *    #    *     #     *     #')
    print()
    print()
    print()
    time.sleep(b)
    print('You are sleeping and all of sudden you are in a dream realm.') 
    time.sleep(b)
    print('You appear in a abandoned hospital and its dark.')
    time.sleep(b)
    print('You are the only one to get out of the hospital before you are permenently trapped in the dream realm.')
    time.sleep(b)
    print('Where you wont be able to get back to your physical body.')
    print()
    print()
    print()
    time.sleep(b)
    print('Hello? Is anyone here? Its so dark in these hallways.')
    print()
    print()
    time.sleep(b)
    print('Where am I? Am I in some hospital? How did I get here????')
    print()
    time.sleep(b)
    print('WOAH!!! What are those in the hallway? I see a light')
    print()
    time.sleep(b)
    print('I walk towards it and its a flashlight. I open up the flashlight and it has 3 batteries inside.')
    print()
    print()
    time.sleep(c)
    print('I am going to pick up this flashlight.')
    time.sleep(c)
    print('I hope it works throughout the time of me being in this creepy hospital.')
    print()
    print()
    time.sleep(b)
    print('Walking into these narrow hallways I see deteriorated rooms ')
    time.sleep(b)
    print('with beds that havent been used for decades.')
    print()
    print()
    time.sleep(b)
    print('I look to my right and I see another room the same as the others but this one has a painting.')
    print()
    print()
    time.sleep(c)
    print('I walk towards the room where the painting is in and I take a closer look at it.')
    time.sleep(c)
    print('It looks like a patient who passed away.')
    print()
    print()
    print()
    time.sleep(b)
    print('************ WIND HAS RUSHED THROUGH ME ************')
    print()
    print()
    print()
    time.sleep(b)
    print('What was that???')
    time.sleep(c)
    print('I take my flashlight to see if anyone was in the room or near the room and no one was there.')
    time.sleep(a)
    print('Thats weird…')
    print()
    print()
    print()
    time.sleep(b)
    print('************ HUMMING NOISES ACCROSS THE HALLWAY ************')
    print()
    print()
    print()
    time.sleep(c)
    print('Hellooooooooo? Is anyone here with me?')
    print() 
    print()
    print()
    time.sleep(b)
    print('************ LAUGHING SOUNDS STARTS TO APPEAR THEN FADES ************')
    print()
    print()
    print()
    time.sleep(b)
    print('************ GASPED LOUDLY ************')
    print()
    print()
    print()
    time.sleep(c)
    print('I saw two nearest exits but I also saw a bathroom.')
    time.sleep(c)
    print('The laughing noise started to appear again but its getting closer.')
    print()
    print()
    time.sleep(c)    
    answer = input('#1: Go to the 1st exit || #2: Go to the 2nd exit || #3: Go to the bathroom and hide: ')
    if answer == '#1' or answer == 'Go to the 1st exit' or '#1: Go to the 1st exit':
            print()
            print()
            time.sleep(c)
            print('I ran to the first exit and I opened the door.')
            time.sleep(c)
            print('Its pitch black but as I kept walking with my flashlight on, ')
            time.sleep(c)
            print('the flashlight started to flicker and it turned off.')
            print()
            print()
            time.sleep(b)
            print('I tapped the flashlight three times and no light is coming up')
            print()
            print()
            time.sleep(b)
            print('Oh my voice again and I cant see anything at all. It was getting closer.')
            print()
            print()
            time.sleep(b)
            print('AHHHHHHHHHH')
            print()
            print()
            print()
            time.sleep(b)
            print('************ FALLING INTO A BLACK HOLE ************')
            print()
            print()
            print()
            time.sleep(c)
            print('Y O U    A R E   D E A D !!!')
            print()
            print()

    elif answer == '#2' or answer == 'Go to the 2nd exit' or answer == '#2: Go to the 2nd exit':
            print()
            print()
            time.sleep(c)
            print('I ran to the second exit and I opened the door as quickly as possible.')
            time.sleep(c)
            print('I kept running and I lit up like a bright purple.')
            time.sleep(c)
            print('I didnt think too much about it so I kept running.')
            print()
            print()
            print()
            time.sleep(b)
            print('************ RETURNED BACK TO THE PHYSICAL REALM ************')
            print()
            print()
            print()
            print('************ BREATHING HEAVILY ************')
            print()
            print()
            print()
            time.sleep(b)
            print('Oh it was just a nightmare. It felt so real…')
            print()
            print()
            print()
            time.sleep(c)
            print('T H E  E N D !!!')
            print()
            print()

    elif answer == '#3' or answer == 'Go to the bathroom and hide' or answer == '#3: Go to the bathroom and hide':
            print()
            print()
            time.sleep(a)
            print('I am running to the bathroom since its next to the room I was in minutes ago.')
            print()
            print()
            time.sleep(c)
            print('I got into one of the bathroom stalls, got on top of the toilet and bent down.')
            print()
            print()
            time.sleep(b)
            print('I turned off the flashlight. I covered my mouth with both hands.')
            print()
            print()
            time.sleep(b)
            print('I stayed still and made no noise but I was shaking with fear.')
            print()
            print()
            time.sleep(b)
            print('I heard a door open and it was the bathroom door.')
            print()
            print()
            time.sleep(b)
            print('I heard footsteps.')
            print()
            print()
            time.sleep(c)
            print('Whatever it is, is checking each bathroom stall.')
            print()
            print()
            time.sleep(c)
            print('I have to get out but its going to catch me and possibly kill me.')
            print()
            print()
            time.sleep(b)
            print('Then I hear it in front of the bathroom stall I am in.')
            print()
            print()
            print()
            time.sleep(b)
            print('************ SHAKING EVEN MORE ************')
            print()
            print()
            print()
            time.sleep(c)
            print('It tried to open the stall but it isnt opening.')
            print()
            print()
            time.sleep(c)
            print('All of a sudden it started to bang on the bathroom stall ')
            time.sleep(c)
            print('and tried to shake the door of it so it could open.')
            print()
            print()
            time.sleep(b)
            print('I know you are in there.')
            print()
            print()
            print()
            time.sleep(b)
            print('************ GLOWING EYES ONTOP OF BATHROOM STALL ************')
            print()
            print()
            print()
            time.sleep(b)
            print('GOT YOU!')
            print()
            print()
            print()
            time.sleep(b)
            print('************ GRABBED THE NECK AND TWISTS IT ************')
            print()
            print()
            print()
            time.sleep(c)
            print('Y O U   A R E   D E A D !!!') 
    break